language: python
python:
    - "3.5"

sudo: false
cache: pip

services:
  - mongodb

before_script:
  - pip install tox
  - ./bootstrap_mongodb.sh
  - python abell-db-setup.py

script:
  - tox
  - python functional_tests.py
