language: python
python:
    - "3.5"

sudo: false
cache: pip

services:
  - mongodb

before_script:
  - pip install tox
  - mongo abell --eval 'use admin; db.createUser({user: "admin", password:"password", roles:["userAdminAnyDatabase"]});'
  - python abell-db-setup.py

script:
  - tox
  - python functional_tests.py
